services:
  db:
    image: postgres:14
    container_name: postgres_ag
    environment:
      POSTGRES_USER: brain_ag_user
      POSTGRES_PASSWORD: brain_ag_password
      POSTGRES_DB: brain_ag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
